name: serious_game
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.4.1
  flutter_native_splash: ^2.4.2
  dio: ^5.7.0
  flutter_slider_drawer: ^2.1.3
  get: ^4.6.6
  dropdown_textfield: ^1.2.0
  photo_view: ^0.15.0
  interactive_image: ^7.0.0
  path_provider: ^2.1.5
  file_picker: ^10.2.0
  collection: 1.19.0
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/configuration.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Black.ttf
          weight: 900
        - asset: assets/fonts/Kanit-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Kanit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Kanit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Kanit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Kanit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Kanit-Medium.ttf
          weight: 500
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
